# Generated by Django 5.2.4 on 2025-09-02 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root', models.BooleanField(default=False)),
                ('node_type', models.CharField(choices=[('folder', 'Folder'), ('entry', 'Entry')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('name', models.CharField(max_length=32)),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='folder', related_query_name='folders', serialize=False, to='main.node')),
            ],
            bases=('main.node',),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'data type',
                'verbose_name_plural': 'data types',
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('create_time', models.DateTimeField(auto_created=True, auto_now=True)),
                ('name', models.CharField(default='', max_length=64)),
                ('context_date', models.DateField(blank=True, null=True)),
                ('context_description', models.TextField(default='', max_length=512)),
                ('file_realid', models.CharField(default='', max_length=64)),
                ('thumbnail', models.CharField(default=None, max_length=64, null=True)),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='entry', related_query_name='entries', serialize=False, to='main.node')),
                ('data_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.type')),
                ('tags', models.ManyToManyField(blank=True, to='main.tag')),
            ],
            options={
                'verbose_name': 'Entry',
                'verbose_name_plural': 'Entries',
            },
            bases=('main.node',),
        ),
        migrations.AddField(
            model_name='node',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_nodes', to='main.folder'),
        ),
    ]
