# Generated by Django 5.2.4 on 2025-07-19 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root', models.BooleanField(default=False)),
                ('node_type', models.CharField(choices=[('folder', 'Folder'), ('data_entry', 'Data')])),
                ('parent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_nodes', to='main.node')),
            ],
        ),
        migrations.CreateModel(
            name='DataTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
            },
        ),
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Data type',
                'verbose_name_plural': 'Data types',
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('node_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.node')),
                ('name', models.CharField(max_length=32)),
            ],
            bases=('main.node',),
        ),
        migrations.CreateModel(
            name='DataEntry',
            fields=[
                ('create_time', models.DateTimeField(auto_created=True, auto_now=True)),
                ('title', models.CharField(default='', max_length=64)),
                ('context_date', models.DateField(blank=True, null=True)),
                ('context_description', models.TextField(default='', max_length=512)),
                ('file_realid', models.CharField(default='', max_length=64)),
                ('thumbnail', models.CharField(default=None, max_length=64, null=True)),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='data_entry', related_query_name='data_entries', serialize=False, to='main.node')),
                ('data_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.datatype')),
                ('tags', models.ManyToManyField(to='main.datatag')),
            ],
            options={
                'verbose_name': 'Data',
                'verbose_name_plural': 'Data',
            },
            bases=('main.node',),
        ),
    ]
