# Generated by Django 5.2.4 on 2025-07-06 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_node', related_query_name='parent_nodes', to='main.node')),
            ],
        ),
        migrations.RenameField(
            model_name='dataentry',
            old_name='date',
            new_name='context_date',
        ),
        migrations.RemoveField(
            model_name='dataentry',
            name='file',
        ),
        migrations.AddField(
            model_name='dataentry',
            name='context_description',
            field=models.TextField(default='', max_length=512),
        ),
        migrations.CreateModel(
            name='DataNode',
            fields=[
                ('node_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.node')),
                ('data_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.dataentry')),
            ],
            bases=('main.node',),
        ),
        migrations.CreateModel(
            name='FolderNode',
            fields=[
                ('node_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.node')),
                ('name', models.CharField(max_length=32)),
                ('children', models.ManyToManyField(related_name='children_node', related_query_name='children_nodes', to='main.node')),
            ],
            bases=('main.node',),
        ),
    ]
