# Generated by Django 5.2.4 on 2025-07-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataentry',
            old_name='date',
            new_name='context_date',
        ),
        migrations.RemoveField(
            model_name='dataentry',
            name='file',
        ),
        migrations.AddField(
            model_name='dataentry',
            name='context_description',
            field=models.TextField(default='', max_length=512),
        ),
    ]
