# Generated by Django 5.2.4 on 2025-09-13 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='path',
            field=models.CharField(blank=True, editable=False, max_length=256),
        ),
    ]
