# Generated by Django 5.2.4 on 2025-07-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_dataentry_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentry',
            name='context_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
