# Generated by Django 5.2.4 on 2025-08-15 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_node_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='title',
            new_name='name',
        ),
    ]
