// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/signup": {
    params: {};
  };
  "/catalog": {
    params: {};
  };
  "/catalog/:entryId": {
    params: {
      "entryId": string;
    };
  };
  "/password-reset": {
    params: {};
  };
  "/oauth-success": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/signup" | "/catalog" | "/catalog/:entryId" | "/password-reset" | "/oauth-success";
  };
  "main.tsx": {
    id: "main";
    page: "/" | "/signup" | "/catalog" | "/catalog/:entryId" | "/password-reset" | "/oauth-success";
  };
  "routes/Main.tsx": {
    id: "routes/Main";
    page: "/" | "/signup" | "/catalog" | "/catalog/:entryId" | "/password-reset" | "/oauth-success";
  };
  "routes/Index.tsx": {
    id: "routes/Index";
    page: "/";
  };
  "routes/Signup.tsx": {
    id: "routes/Signup";
    page: "/signup";
  };
  "routes/Catalog.tsx": {
    id: "routes/Catalog";
    page: "/catalog" | "/catalog/:entryId";
  };
  "routes/CatalogIndex.tsx": {
    id: "routes/CatalogIndex";
    page: "/catalog";
  };
  "routes/CatalogEntry.tsx": {
    id: "routes/CatalogEntry";
    page: "/catalog/:entryId";
  };
  "routes/PassReset.tsx": {
    id: "routes/PassReset";
    page: "/password-reset";
  };
  "routes/OauthSuccess.tsx": {
    id: "routes/OauthSuccess";
    page: "/oauth-success";
  };
};