// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/signup": {
    params: {};
  };
  "/catalog": {
    params: {};
  };
  "/auth": {
    params: {};
  };
  "/account": {
    params: {};
  };
  "/password-reset": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/signup" | "/catalog" | "/auth" | "/account" | "/password-reset";
  };
  "routes/Main.tsx": {
    id: "routes/Main";
    page: "/" | "/signup" | "/catalog" | "/auth" | "/account" | "/password-reset";
  };
  "routes/Index.tsx": {
    id: "routes/Index";
    page: "/" | "/signup";
  };
  "routes/Login.tsx": {
    id: "routes/Login";
    page: "/";
  };
  "routes/Signup.tsx": {
    id: "routes/Signup";
    page: "/signup";
  };
  "routes/Catalog.tsx": {
    id: "routes/Catalog";
    page: "/catalog";
  };
  "routes/Auth.tsx": {
    id: "routes/Auth";
    page: "/auth";
  };
  "routes/Account.tsx": {
    id: "routes/Account";
    page: "/account";
  };
  "routes/PassReset.tsx": {
    id: "routes/PassReset";
    page: "/password-reset";
  };
};