# Generated by Django 5.2.4 on 2025-10-01 10:41

import auth_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='services',
            field=models.JSONField(default=list, validators=[auth_app.models.service_name_validator]),
        ),
    ]
