# Generated by Django 5.2.4 on 2025-08-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_access_token',
            field=models.TextField(default=None, max_length=255, null=True, verbose_name='Google API access token'),
        ),
        migrations.AddField(
            model_name='user',
            name='google_refresh_token',
            field=models.TextField(default=None, max_length=255, null=True, verbose_name='Google API refresh token'),
        ),
    ]
