# Generated by Django 5.2.4 on 2025-10-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_user_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='google_access_token',
            field=models.TextField(blank=True, default=None, max_length=255, null=True, verbose_name='Google API access token'),
        ),
        migrations.AlterField(
            model_name='user',
            name='google_refresh_token',
            field=models.TextField(blank=True, default=None, max_length=255, null=True, verbose_name='Google API refresh token'),
        ),
    ]
