# Generated by Django 5.2.4 on 2025-10-01 12:38

import auth_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_user_google_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='services',
            field=models.JSONField(default=['service_names', 'last_used_service'], validators=[auth_app.models.service_name_validator]),
        ),
    ]
