# Generated by Django 5.2.4 on 2025-10-01 12:53

import auth_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_alter_user_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='services',
            field=models.JSONField(default=list, validators=[auth_app.models.service_name_validator]),
        ),
    ]
