# Generated by Django 5.2.4 on 2025-10-01 12:57

import auth_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_alter_user_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='services',
            field=models.JSONField(default=dict, validators=[auth_app.models.service_name_validator]),
        ),
    ]
